### ISSUE TITLE
Mod says it is compatible with minecraft 1.20.1 but requires anything between 1.18 or 1.19

### ISSUE THREAD

**Issue by MidasMischief** [KawaiiZapic/ClockHUD#1]
As the title suggests

**Comment by KawaiiZapic** [comment]
Take a carefully look at the file name.  
`clock-hud_{supported_game_version}-{mod_version}`, it's working fine in my game.
`clock-hud_1.20.4-1.1.8.jar` should support any version between `1.20 ~ 1.20.6`

**Comment by KawaiiZapic** [comment]
@MidasMischief Hello, I would like to know if you solved this problem. I will keep tracking on this issue, feel free to leave any comments.
